library(DBI)
library(rJava)
.jinit(force.init = TRUE)
print(.jcall("java/lang/System", "S", "getProperty", "java.version"))
library(RJDBC)
library(sqldf)
library(ggplot2)
library(scales)
library(data.table)
library(zoo)
drv <- JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver","/opt/sqljdbc_3.0/sqljdbc4.jar")